apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: real-devops-challenge
  labels:
    type: local
spec:
  capacity:
    storage: 300M
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo-pv"
---